export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const TRY_LOGIN = 'try_login'
export const ON_LOGIN_SUCCESS = 'login_success'
export const ON_LOGIN_FAILED = 'login_failed'
export const TRY_SIGNOUT = 'try_signout'
export const ON_SIGNOUT_SUCCESS = 'signout_success'
export const ON_SIGNOUT_FAILED = 'signout_failed'
